# Generated by Django 4.1 on 2022-08-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_postovi_sadrzaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='postovi',
            name='naslov_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
