# Generated by Django 4.1 on 2022-08-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0004_postovi_datum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postovi',
            options={'verbose_name_plural': 'Postovi'},
        ),
    ]
