# Generated by Django 4.1 on 2022-08-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0006_kategorija_postovi_kategorija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postovi',
            name='kategorija',
            field=models.CharField(default='Ostalo', max_length=255),
        ),
    ]
