# Generated by Django 4.1 on 2022-08-04 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog1', '0007_alter_postovi_kategorija'),
    ]

    operations = [
        migrations.AddField(
            model_name='postovi',
            name='lajkovi',
            field=models.ManyToManyField(related_name='blogposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
