# Generated by Django 4.1 on 2022-08-05 08:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0008_postovi_lajkovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postovi',
            name='sadrzaj',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
