# Generated by Django 4.1 on 2022-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0009_alter_postovi_sadrzaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='postovi',
            name='snippet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
