# Generated by Django 4.1 on 2022-08-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0011_korisnickiprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='postovi',
            name='header_slika',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='korisnickiprofil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
