# Generated by Django 4.1 on 2022-08-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0012_postovi_header_slika_alter_korisnickiprofil_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnickiprofil',
            name='fb_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='korisnickiprofil',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='korisnickiprofil',
            name='profil_slika',
            field=models.ImageField(blank=True, null=True, upload_to='images/profilke/'),
        ),
        migrations.AddField(
            model_name='korisnickiprofil',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
