# Generated by Django 4.1 on 2022-08-07 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0013_korisnickiprofil_fb_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_komentatora', models.CharField(max_length=255)),
                ('sadrzaj', models.TextField()),
                ('datum_komentara', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentari', to='blog1.postovi')),
            ],
        ),
    ]
