# Generated by Django 4.1 on 2022-08-10 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog1', '0014_komentari'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentari',
            name='lajkovi_za_koment',
            field=models.ManyToManyField(related_name='blogcomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
